//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetKeyer.Resources.Strings {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetKeyer.Resources.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About NetKeyer.
        /// </summary>
        public static string AboutWindow_Title {
            get {
                return ResourceManager.GetString("AboutWindow_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NetKeyer.
        /// </summary>
        public static string AboutWindow_AppName {
            get {
                return ResourceManager.GetString("AboutWindow_AppName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to by Andrew KC2G and NetKeyer contributors.
        /// </summary>
        public static string AboutWindow_Credits {
            get {
                return ResourceManager.GetString("AboutWindow_Credits", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string AboutWindow_CheckForUpdates {
            get {
                return ResourceManager.GetString("AboutWindow_CheckForUpdates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string AboutWindow_Close {
            get {
                return ResourceManager.GetString("AboutWindow_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string AboutWindow_Version_Format {
            get {
                return ResourceManager.GetString("AboutWindow_Version_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version unknown.
        /// </summary>
        public static string AboutWindow_Version_Unknown {
            get {
                return ResourceManager.GetString("AboutWindow_Version_Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string AboutWindow_Update_Checking {
            get {
                return ResourceManager.GetString("AboutWindow_Update_Checking", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to App is not installed via Velopack (running in development mode).
        /// </summary>
        public static string AboutWindow_Update_NotInstalled {
            get {
                return ResourceManager.GetString("AboutWindow_Update_NotInstalled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are running the latest version!.
        /// </summary>
        public static string AboutWindow_Update_Latest {
            get {
                return ResourceManager.GetString("AboutWindow_Update_Latest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update available: {0}.
        /// </summary>
        public static string AboutWindow_Update_Available {
            get {
                return ResourceManager.GetString("AboutWindow_Update_Available", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Downloading update....
        /// </summary>
        public static string AboutWindow_Update_Downloading {
            get {
                return ResourceManager.GetString("AboutWindow_Update_Downloading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Downloading update... {0}%.
        /// </summary>
        public static string AboutWindow_Update_DownloadingPercent {
            get {
                return ResourceManager.GetString("AboutWindow_Update_DownloadingPercent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restarting to apply update....
        /// </summary>
        public static string AboutWindow_Update_Restarting {
            get {
                return ResourceManager.GetString("AboutWindow_Update_Restarting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update downloaded - restart app to install.
        /// </summary>
        public static string AboutWindow_Update_Downloaded {
            get {
                return ResourceManager.GetString("AboutWindow_Update_Downloaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update check failed: {0}.
        /// </summary>
        public static string AboutWindow_Update_Failed {
            get {
                return ResourceManager.GetString("AboutWindow_Update_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update check timed out after 30 seconds. Please check your internet connection and try again..
        /// </summary>
        public static string AboutWindow_Update_Timeout {
            get {
                return ResourceManager.GetString("AboutWindow_Update_Timeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update Ready.
        /// </summary>
        public static string AboutWindow_UpdateDialog_Title {
            get {
                return ResourceManager.GetString("AboutWindow_UpdateDialog_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version {0} has been downloaded.\n\nWould you like to restart and install it now?.
        /// </summary>
        public static string AboutWindow_UpdateDialog_Message {
            get {
                return ResourceManager.GetString("AboutWindow_UpdateDialog_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update Check Failed.
        /// </summary>
        public static string AboutWindow_UpdateDialog_FailedTitle {
            get {
                return ResourceManager.GetString("AboutWindow_UpdateDialog_FailedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to check for updates:\n\n{0}\n\nCheck the debug log for more details..
        /// </summary>
        public static string AboutWindow_UpdateDialog_FailedMessage {
            get {
                return ResourceManager.GetString("AboutWindow_UpdateDialog_FailedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Audio Output Device Selection.
        /// </summary>
        public static string AudioDevice_Title {
            get {
                return ResourceManager.GetString("AudioDevice_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select the audio output device for sidetone. Changes take effect immediately..
        /// </summary>
        public static string AudioDevice_Instructions {
            get {
                return ResourceManager.GetString("AudioDevice_Instructions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Audio Output Device:.
        /// </summary>
        public static string AudioDevice_Label {
            get {
                return ResourceManager.GetString("AudioDevice_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select an audio device....
        /// </summary>
        public static string AudioDevice_Placeholder {
            get {
                return ResourceManager.GetString("AudioDevice_Placeholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string AudioDevice_Refresh {
            get {
                return ResourceManager.GetString("AudioDevice_Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aggressive Low-Latency Mode (Windows only).
        /// </summary>
        public static string AudioDevice_AggressiveLowLatency {
            get {
                return ResourceManager.GetString("AudioDevice_AggressiveLowLatency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When enabled: Lowest latency, may cause audio artifacts.
        /// </summary>
        public static string AudioDevice_AggressiveEnabled {
            get {
                return ResourceManager.GetString("AudioDevice_AggressiveEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When disabled: Higher latency, most compatible.
        /// </summary>
        public static string AudioDevice_AggressiveDisabled {
            get {
                return ResourceManager.GetString("AudioDevice_AggressiveDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AudioDevice_Cancel {
            get {
                return ResourceManager.GetString("AudioDevice_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AudioDevice_OK {
            get {
                return ResourceManager.GetString("AudioDevice_OK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System Default.
        /// </summary>
        public static string AudioDevice_SystemDefault {
            get {
                return ResourceManager.GetString("AudioDevice_SystemDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Button_Connect {
            get {
                return ResourceManager.GetString("Button_Connect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Button_Disconnect {
            get {
                return ResourceManager.GetString("Button_Disconnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Button_Exit {
            get {
                return ResourceManager.GetString("Button_Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Common_Refresh {
            get {
                return ResourceManager.GetString("Common_Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CW Settings.
        /// </summary>
        public static string CWSettings_Title {
            get {
                return ResourceManager.GetString("CWSettings_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Speed (WPM):.
        /// </summary>
        public static string CWSettings_Speed {
            get {
                return ResourceManager.GetString("CWSettings_Speed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sidetone:.
        /// </summary>
        public static string CWSettings_Sidetone {
            get {
                return ResourceManager.GetString("CWSettings_Sidetone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pitch (Hz):.
        /// </summary>
        public static string CWSettings_Pitch {
            get {
                return ResourceManager.GetString("CWSettings_Pitch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keyer Mode:.
        /// </summary>
        public static string CWSettings_KeyerMode {
            get {
                return ResourceManager.GetString("CWSettings_KeyerMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Iambic.
        /// </summary>
        public static string CWSettings_Iambic {
            get {
                return ResourceManager.GetString("CWSettings_Iambic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Straight Key.
        /// </summary>
        public static string CWSettings_StraightKey {
            get {
                return ResourceManager.GetString("CWSettings_StraightKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Iambic Type:.
        /// </summary>
        public static string CWSettings_IambicType {
            get {
                return ResourceManager.GetString("CWSettings_IambicType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mode A.
        /// </summary>
        public static string CWSettings_ModeA {
            get {
                return ResourceManager.GetString("CWSettings_ModeA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mode B.
        /// </summary>
        public static string CWSettings_ModeB {
            get {
                return ResourceManager.GetString("CWSettings_ModeB", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Swap Paddles (Left ↔ Right).
        /// </summary>
        public static string CWSettings_SwapPaddles {
            get {
                return ResourceManager.GetString("CWSettings_SwapPaddles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input Device Selection.
        /// </summary>
        public static string InputDevice_Title {
            get {
                return ResourceManager.GetString("InputDevice_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input Type:.
        /// </summary>
        public static string InputDevice_Type {
            get {
                return ResourceManager.GetString("InputDevice_Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Serial Port (HaliKey v1).
        /// </summary>
        public static string InputDevice_SerialPort {
            get {
                return ResourceManager.GetString("InputDevice_SerialPort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MIDI (HaliKey MIDI, CTR2).
        /// </summary>
        public static string InputDevice_Midi {
            get {
                return ResourceManager.GetString("InputDevice_Midi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string InputDevice_Port {
            get {
                return ResourceManager.GetString("InputDevice_Port", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a port....
        /// </summary>
        public static string InputDevice_PortPlaceholder {
            get {
                return ResourceManager.GetString("InputDevice_PortPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MIDI Device:.
        /// </summary>
        public static string InputDevice_MidiDevice {
            get {
                return ResourceManager.GetString("InputDevice_MidiDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a MIDI device....
        /// </summary>
        public static string InputDevice_MidiPlaceholder {
            get {
                return ResourceManager.GetString("InputDevice_MidiPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key Status.
        /// </summary>
        public static string KeyStatus_Title {
            get {
                return ResourceManager.GetString("KeyStatus_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Left Paddle.
        /// </summary>
        public static string KeyStatus_LeftPaddle {
            get {
                return ResourceManager.GetString("KeyStatus_LeftPaddle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Right Paddle.
        /// </summary>
        public static string KeyStatus_RightPaddle {
            get {
                return ResourceManager.GetString("KeyStatus_RightPaddle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string KeyStatus_Key {
            get {
                return ResourceManager.GetString("KeyStatus_Key", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PTT.
        /// </summary>
        public static string KeyStatus_PTT {
            get {
                return ResourceManager.GetString("KeyStatus_PTT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string KeyStatus_On {
            get {
                return ResourceManager.GetString("KeyStatus_On", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string KeyStatus_Off {
            get {
                return ResourceManager.GetString("KeyStatus_Off", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MacMenu_File {
            get {
                return ResourceManager.GetString("MacMenu_File", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MacMenu_Exit {
            get {
                return ResourceManager.GetString("MacMenu_Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MacMenu_Settings {
            get {
                return ResourceManager.GetString("MacMenu_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Audio Output Device....
        /// </summary>
        public static string MacMenu_AudioDevice {
            get {
                return ResourceManager.GetString("MacMenu_AudioDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MIDI Note Mapping....
        /// </summary>
        public static string MacMenu_MidiMapping {
            get {
                return ResourceManager.GetString("MacMenu_MidiMapping", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MacMenu_Help {
            get {
                return ResourceManager.GetString("MacMenu_Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string MacMenu_Documentation {
            get {
                return ResourceManager.GetString("MacMenu_Documentation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About NetKeyer....
        /// </summary>
        public static string MacMenu_About {
            get {
                return ResourceManager.GetString("MacMenu_About", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NetKeyer - FlexRadio CW Keyer.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Audio Output Device....
        /// </summary>
        public static string Menu_Settings_AudioDevice {
            get {
                return ResourceManager.GetString("Menu_Settings_AudioDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _MIDI Note Mapping....
        /// </summary>
        public static string Menu_Settings_MidiMapping {
            get {
                return ResourceManager.GetString("Menu_Settings_MidiMapping", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _Documentation.
        /// </summary>
        public static string Menu_Help_Documentation {
            get {
                return ResourceManager.GetString("Menu_Help_Documentation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _View Debug Log....
        /// </summary>
        public static string Menu_Help_ViewDebugLog {
            get {
                return ResourceManager.GetString("Menu_Help_ViewDebugLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to _About NetKeyer....
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MIDI Note Configuration.
        /// </summary>
        public static string MidiConfig_Title {
            get {
                return ResourceManager.GetString("MidiConfig_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Assign MIDI notes (0-127) to one or more functions. Multiple functions can be assigned to the same note..
        /// </summary>
        public static string MidiConfig_Instructions {
            get {
                return ResourceManager.GetString("MidiConfig_Instructions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Note:.
        /// </summary>
        public static string MidiConfig_AddNote {
            get {
                return ResourceManager.GetString("MidiConfig_AddNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string MidiConfig_Add {
            get {
                return ResourceManager.GetString("MidiConfig_Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (MIDI note 0-127).
        /// </summary>
        public static string MidiConfig_NoteRange {
            get {
                return ResourceManager.GetString("MidiConfig_NoteRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Note #.
        /// </summary>
        public static string MidiConfig_NoteNumber {
            get {
                return ResourceManager.GetString("MidiConfig_NoteNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Left Paddle.
        /// </summary>
        public static string MidiConfig_LeftPaddle {
            get {
                return ResourceManager.GetString("MidiConfig_LeftPaddle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Right Paddle.
        /// </summary>
        public static string MidiConfig_RightPaddle {
            get {
                return ResourceManager.GetString("MidiConfig_RightPaddle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Straight Key.
        /// </summary>
        public static string MidiConfig_StraightKey {
            get {
                return ResourceManager.GetString("MidiConfig_StraightKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PTT.
        /// </summary>
        public static string MidiConfig_PTT {
            get {
                return ResourceManager.GetString("MidiConfig_PTT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string MidiConfig_Remove {
            get {
                return ResourceManager.GetString("MidiConfig_Remove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Function Descriptions:.
        /// </summary>
        public static string MidiConfig_FunctionDescriptions {
            get {
                return ResourceManager.GetString("MidiConfig_FunctionDescriptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Left Paddle: Used as dit paddle in iambic mode.
        /// </summary>
        public static string MidiConfig_LeftPaddleDesc {
            get {
                return ResourceManager.GetString("MidiConfig_LeftPaddleDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Right Paddle: Used as dah paddle in iambic mode.
        /// </summary>
        public static string MidiConfig_RightPaddleDesc {
            get {
                return ResourceManager.GetString("MidiConfig_RightPaddleDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Straight Key: Key down/up in straight key mode.
        /// </summary>
        public static string MidiConfig_StraightKeyDesc {
            get {
                return ResourceManager.GetString("MidiConfig_StraightKeyDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PTT: Push-to-talk for non-CW modes.
        /// </summary>
        public static string MidiConfig_PTTDesc {
            get {
                return ResourceManager.GetString("MidiConfig_PTTDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset to Defaults.
        /// </summary>
        public static string MidiConfig_ResetToDefaults {
            get {
                return ResourceManager.GetString("MidiConfig_ResetToDefaults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MidiConfig_Cancel {
            get {
                return ResourceManager.GetString("MidiConfig_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MidiConfig_OK {
            get {
                return ResourceManager.GetString("MidiConfig_OK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Mode_Disconnected {
            get {
                return ResourceManager.GetString("Mode_Disconnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sidetone Only.
        /// </summary>
        public static string Mode_SidetoneOnly {
            get {
                return ResourceManager.GetString("Mode_SidetoneOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CW (Iambic Mode A).
        /// </summary>
        public static string Mode_CW_IambicModeA {
            get {
                return ResourceManager.GetString("Mode_CW_IambicModeA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CW (Iambic Mode B).
        /// </summary>
        public static string Mode_CW_IambicModeB {
            get {
                return ResourceManager.GetString("Mode_CW_IambicModeB", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CW (Straight Key).
        /// </summary>
        public static string Mode_CW_StraightKey {
            get {
                return ResourceManager.GetString("Mode_CW_StraightKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} (PTT).
        /// </summary>
        public static string Mode_PTT_Format {
            get {
                return ResourceManager.GetString("Mode_PTT_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Mode_PTT_Unknown {
            get {
                return ResourceManager.GetString("Mode_PTT_Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switch radio to CW mode to activate CW keying.
        /// </summary>
        public static string Mode_SwitchToCW {
            get {
                return ResourceManager.GetString("Mode_SwitchToCW", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Radio Selection.
        /// </summary>
        public static string RadioSelection_Title {
            get {
                return ResourceManager.GetString("RadioSelection_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a radio and station....
        /// </summary>
        public static string RadioSelection_Placeholder {
            get {
                return ResourceManager.GetString("RadioSelection_Placeholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RadioSelection_Refresh {
            get {
                return ResourceManager.GetString("RadioSelection_Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No radio (sidetone only).
        /// </summary>
        public static string RadioSelection_SidetoneOnly {
            get {
                return ResourceManager.GetString("RadioSelection_SidetoneOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Stations.
        /// </summary>
        public static string RadioSelection_NoStations {
            get {
                return ResourceManager.GetString("RadioSelection_NoStations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) - {2} [{3}].
        /// </summary>
        public static string RadioSelection_Format_LocalRadio {
            get {
                return ResourceManager.GetString("RadioSelection_Format_LocalRadio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) - No Stations.
        /// </summary>
        public static string RadioSelection_Format_LocalRadioNoStation {
            get {
                return ResourceManager.GetString("RadioSelection_Format_LocalRadioNoStation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [SmartLink] {0} ({1}) - {2} [{3}].
        /// </summary>
        public static string RadioSelection_Format_SmartLinkRadio {
            get {
                return ResourceManager.GetString("RadioSelection_Format_SmartLinkRadio", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [SmartLink] {0} ({1}) - No Stations.
        /// </summary>
        public static string RadioSelection_Format_SmartLinkRadioNoStation {
            get {
                return ResourceManager.GetString("RadioSelection_Format_SmartLinkRadioNoStation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No radio/client selected.
        /// </summary>
        public static string RadioSelection_Error_NoRadioSelected {
            get {
                return ResourceManager.GetString("RadioSelection_Error_NoRadioSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No station available.
        /// </summary>
        public static string RadioSelection_Error_NoStationAvailable {
            get {
                return ResourceManager.GetString("RadioSelection_Error_NoStationAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not connected to SmartLink server.
        /// </summary>
        public static string RadioSelection_Error_NotConnectedToServer {
            get {
                return ResourceManager.GetString("RadioSelection_Error_NotConnectedToServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Requesting SmartLink connection....
        /// </summary>
        public static string RadioSelection_Error_RequestingConnection {
            get {
                return ResourceManager.GetString("RadioSelection_Error_RequestingConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SmartLink connection request timed out.
        /// </summary>
        public static string RadioSelection_Error_ConnectionTimeout {
            get {
                return ResourceManager.GetString("RadioSelection_Error_ConnectionTimeout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to get SmartLink connection handle.
        /// </summary>
        public static string RadioSelection_Error_NoConnectionHandle {
            get {
                return ResourceManager.GetString("RadioSelection_Error_NoConnectionHandle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connecting to radio via SmartLink....
        /// </summary>
        public static string RadioSelection_Error_ConnectingViaSmartLink {
            get {
                return ResourceManager.GetString("RadioSelection_Error_ConnectingViaSmartLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to radio.
        /// </summary>
        public static string RadioSelection_Error_FailedToConnect {
            get {
                return ResourceManager.GetString("RadioSelection_Error_FailedToConnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to find station after connection.
        /// </summary>
        public static string RadioSelection_Error_StationNotFound {
            get {
                return ResourceManager.GetString("RadioSelection_Error_StationNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client UUID not available - binding may fail.
        /// </summary>
        public static string RadioSelection_Error_UuidNotAvailable {
            get {
                return ResourceManager.GetString("RadioSelection_Error_UuidNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disconnected (radio removed).
        /// </summary>
        public static string RadioSelection_Disconnected_RadioRemoved {
            get {
                return ResourceManager.GetString("RadioSelection_Disconnected_RadioRemoved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login cancelled.
        /// </summary>
        public static string RadioSelection_LoginCancelled {
            get {
                return ResourceManager.GetString("RadioSelection_LoginCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login failed - check credentials.
        /// </summary>
        public static string RadioSelection_LoginFailed {
            get {
                return ResourceManager.GetString("RadioSelection_LoginFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to show login dialog.
        /// </summary>
        public static string RadioSelection_ShowDialogFailed {
            get {
                return ResourceManager.GetString("RadioSelection_ShowDialogFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language changes will take effect after restarting the application..
        /// </summary>
        public static string Settings_LanguageRestartRequired {
            get {
                return ResourceManager.GetString("Settings_LanguageRestartRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SmartLink.
        /// </summary>
        public static string SmartLink_Title {
            get {
                return ResourceManager.GetString("SmartLink_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login to SmartLink.
        /// </summary>
        public static string SmartLink_LoginButton {
            get {
                return ResourceManager.GetString("SmartLink_LoginButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logout from SmartLink.
        /// </summary>
        public static string SmartLink_LogoutButton {
            get {
                return ResourceManager.GetString("SmartLink_LogoutButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retry Login.
        /// </summary>
        public static string SmartLink_RetryButton {
            get {
                return ResourceManager.GetString("SmartLink_RetryButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string SmartLink_Status_NotConnected {
            get {
                return ResourceManager.GetString("SmartLink_Status_NotConnected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        public static string SmartLink_Status_NotLoggedIn {
            get {
                return ResourceManager.GetString("SmartLink_Status_NotLoggedIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        public static string SmartLink_Status_Authenticating {
            get {
                return ResourceManager.GetString("SmartLink_Status_Authenticating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authenticated.
        /// </summary>
        public static string SmartLink_Status_Authenticated {
            get {
                return ResourceManager.GetString("SmartLink_Status_Authenticated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authentication error.
        /// </summary>
        public static string SmartLink_Status_AuthenticationError {
            get {
                return ResourceManager.GetString("SmartLink_Status_AuthenticationError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown state.
        /// </summary>
        public static string SmartLink_Status_UnknownState {
            get {
                return ResourceManager.GetString("SmartLink_Status_UnknownState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connected to SmartLink.
        /// </summary>
        public static string SmartLink_Status_ConnectedToServer {
            get {
                return ResourceManager.GetString("SmartLink_Status_ConnectedToServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to SmartLink server.
        /// </summary>
        public static string SmartLink_Status_FailedToConnect {
            get {
                return ResourceManager.GetString("SmartLink_Status_FailedToConnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration invalid - please log in again.
        /// </summary>
        public static string SmartLink_Status_RegistrationInvalid {
            get {
                return ResourceManager.GetString("SmartLink_Status_RegistrationInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No client_id configured.
        /// </summary>
        public static string SmartLink_Status_NoClientId {
            get {
                return ResourceManager.GetString("SmartLink_Status_NoClientId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SmartLink not available - no client_id configured.
        /// </summary>
        public static string SmartLink_Status_NotAvailable {
            get {
                return ResourceManager.GetString("SmartLink_Status_NotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string SmartLink_Error_Prefix {
            get {
                return ResourceManager.GetString("SmartLink_Error_Prefix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SmartLink Login.
        /// </summary>
        public static string SmartLinkLogin_Title {
            get {
                return ResourceManager.GetString("SmartLinkLogin_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign in to SmartLink.
        /// </summary>
        public static string SmartLinkLogin_Header {
            get {
                return ResourceManager.GetString("SmartLinkLogin_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email or Username:.
        /// </summary>
        public static string SmartLinkLogin_UsernameLabel {
            get {
                return ResourceManager.GetString("SmartLinkLogin_UsernameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter your email or username.
        /// </summary>
        public static string SmartLinkLogin_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("SmartLinkLogin_UsernamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string SmartLinkLogin_PasswordLabel {
            get {
                return ResourceManager.GetString("SmartLinkLogin_PasswordLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string SmartLinkLogin_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("SmartLinkLogin_PasswordPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string SmartLinkLogin_RememberMe {
            get {
                return ResourceManager.GetString("SmartLinkLogin_RememberMe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SmartLinkLogin_Cancel {
            get {
                return ResourceManager.GetString("SmartLinkLogin_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string SmartLinkLogin_Login {
            get {
                return ResourceManager.GetString("SmartLinkLogin_Login", resourceCulture);
            }
        }
    }
}
